development:
  address: "smtp.163.com"
  port: 25
  domain: "163.com"
  authentication: "plain"
  user_name: "happywinesong@163.com"
  password: "sjw_980202"
  enable_starttls_auto: true
production:
  address: "smtp.gmail.com"
  port: 587
  domain: "heroku.com"
  authentication: "plain"
  user_name: "happywinesong@gmail.com"
  password: "sjw_980202"
  enable_starttls_auto: true