development:
  address: "smtp.163.com"
  port: 25
  authentication: "plain"
  user_name: "happywinesong@163.com"
  password: "sjw_980202"
  enable_starttls_auto: true
production:
  address: "smtp.163.com"
  port: 25
  authentication: "plain"
  user_name: "happywinesong@163.com"
  password: "sjw_980202"
  enable_starttls_auto: true